define([], function () {
	return {
		ChampionName: "Dr. Mundo",
		CreateDate: 1400564011099,
		FellowPlayers: 
		[
		{
			ChampionName: "Akali",
			ChampionId: 84,
			SummonerId: 32553150,
			SummonerName: "sona13",
			Side: "blue"
		},
		{
			ChampionName: "Karma",
			ChampionId: 43,
			SummonerId: 19584087,
			SummonerName: "Comrade Taters",
			Side: "blue"
		},
		{
			ChampionName: "Vel'Koz",
			ChampionId: 161,
			SummonerId: 34107827,
			SummonerName: "Lvl 66 Umbreon",
			Side: "purple"
		},
		{
			ChampionName: "Soraka",
			ChampionId: 16,
			SummonerId: 36334053,
			SummonerName: "Gummibearmurder",
			Side: "blue"
		},
		{
			ChampionName: "Master Yi",
			ChampionId: 11,
			SummonerId: 22526960,
			SummonerName: "DOH11",
			Side: "purple"
		},
		{
			ChampionName: "Corki",
			ChampionId: 42,
			SummonerId: 27282908,
			SummonerName: "iAmMonument",
			Side: "purple"
		},
		{
			ChampionName: "Graves",
			ChampionId: 104,
			SummonerId: 39936440,
			SummonerName: "iAmNuclearRage",
			Side: "purple"
		},
		{
			ChampionName: "Singed",
			ChampionId: 27,
			SummonerId: 19806129,
			SummonerName: "Jonny two shoes",
			Side: "blue"
		},
		{
			ChampionName: "Sona",
			ChampionId: 37,
			SummonerId: 32268067,
			SummonerName: "The Psitron Kid",
			Side: "purple"
		}
		],
		GameId: 1388140795,
		GameMode: "ARAM",
		GameType: "MATCHED_GAME",
		Invalid: false,
		IpEarned: 43,
		MapId: 12,
		Spell1: 4,
		Spell2: 6,
		Stats: 
		{
			Assists: 9,
			BarracksKilled: 0,
			ChampionsKilled: 7,
			CombatPlayerScore: 0,
			ConsumablesPurchased: 0,
			DamageDealtPlayer: 0,
			DoubleKills: 1,
			FirstBlood: 0,
			Gold: 0,
			GoldEarned: 9475,
			GoldSpent: 8425,
			Item0: 2051,
			Item1: 3047,
			Item2: 3065,
			Item3: 3068,
			Item4: 1011,
			Item5: 0,
			Item6: 2052,
			ItemsPurchased: 0,
			KillingSprees: 1,
			LargestCriticalStrike: 0,
			LargestKillingSpree: 2,
			LargestMultiKill: 2,
			LegendaryItemsCreated: 0,
			Level: 16,
			MagicDamageDealtPlayer: 28234,
			MagicDamageDealtToChampions: 15944,
			MagicDamageTaken: 16793,
			MinionsDenied: 0,
			MinionsKilled: 33,
			NeutralMinionsKilled: 0,
			NeutralMinionsKilledEnemyJungle: 0,
			NeutralMinionsKilledYourJungle: 0,
			NexusKilled: false,
			NodeCapture: 0,
			NodeCaptureAssist: 0,
			NodeNeutralize: 0,
			NodeNeutralizeAssist: 0,
			NumDeaths: 8,
			NumItemsBought: 0,
			ObjectivePlayerScore: 0,
			PentaKills: 0,
			PhysicalDamageDealtPlayer: 9350,
			PhysicalDamageDealtToChampions: 2760,
			PhysicalDamageTaken: 15717,
			QuadraKills: 0,
			SightWardsBought: 0,
			Spell1Cast: 0,
			Spell2Cast: 0,
			Spell3Cast: 0,
			Spell4Cast: 0,
			SummonSpell1Cast: 0,
			SummonSpell2Cast: 0,
			SuperMonsterKilled: 0,
			Team: 100,
			TeamObjective: 0,
			TimePlayed: 1284,
			TotalDamageDealt: 37584,
			TotalDamageDealtToChampions: 18704,
			TotalDamageTaken: 34138,
			TotalHeal: 7143,
			TotalPlayerScore: 0,
			TotalScoreRank: 0,
			TotalTimeCrowdControlDealt: 162,
			TotalUnitsHealed: 1,
			TripleKills: 0,
			TrueDamageDealtPlayer: 0,
			TrueDamageDealtToChampions: 0,
			TrueDamageTaken: 1627,
			TurretsKilled: 0,
			UnrealKills: 0,
			VictoryPointTotal: 0,
			VisionWardsBought: 0,
			WardKilled: 0,
			WardPlaced: 0,
			Win: false
		},
		SubType: "ARAM_UNRANKED_5x5",
		Side: "blue"
	};

})