define([], function () {
	return {
		Id: 20227914,
		ProfileIconId: 512,
		SummonerLevel: 30,
		RevisionDate: 1401405216000,
		SummonerId: 20227914,
		Champions: [
		{
			Id: 103,
			ChampionName: "Ahri",
			Stats: {
				AverageAssists: 0,
				AverageChampionsKilled: 0,
				AverageCombatPlayerScore: 0,
				AverageNodeCapture: 0,
				AverageNodeCaptureAssist: 0,
				AverageNodeNeutralize: 0,
				AverageNodeNeutralizeAssist: 0,
				AverageNumDeaths: 0,
				AverageObjectivePlayerScore: 0,
				AverageTeamObjective: 0,
				AverageTotalPlayerScore: 0,
				BotGamesPlayed: 0,
				KillingSpree: 0,
				MaxAssists: 0,
				MaxChampionsKilled: 14,
				MaxCombatPlayerScore: 0,
				MaxLargestCriticalStrike: 0,
				MaxLargestKillingSpree: 0,
				MaxNodeCapture: 0,
				MaxNodeCaptureAssist: 0,
				MaxNodeNeutralize: 0,
				MaxNodeNeutralizeAssist: 0,
				MaxObjectivePlayerScore: 0,
				MaxTeamObjective: 0,
				MaxTimePlayed: 0,
				MaxTimeSpentLiving: 0,
				MaxTotalPlayerScore: 0,
				MostChampionKillsPerSession: 14,
				MostSpellsCast: 0,
				NormalGamesPlayed: 0,
				RankedPremadeGamesPlayed: 0,
				RankedSoloGamesPlayed: 0,
				TotalAssists: 88,
				TotalChampionKills: 71,
				TotalDamageDealt: 1040169,
				TotalDamageTaken: 206402,
				TotalDeathsPerSession: 69,
				TotalDoubleKills: 5,
				TotalFirstBlood: 0,
				TotalGoldEarned: 105883,
				TotalHeal: 0,
				TotalMagicDamageDealt: 610025,
				TotalMinionKills: 1392,
				TotalNeutralMinionsKilled: 0,
				TotalNodeCapture: 0,
				TotalNodeNeutralize: 0,
				TotalPentaKills: 0,
				TotalPhysicalDamageDealt: 132080,
				TotalQuadraKills: 0,
				TotalSessionsLost: 5,
				TotalSessionsPlayed: 9,
				TotalSessionsWon: 4,
				TotalTripleKills: 1,
				TotalTurretsKilled: 5,
				TotalUnrealKills: 0
			}
		},
		{
			Id: 0,
			ChampionName: "Dr. Mundo",
			Stats: {
				AverageAssists: 0,
				AverageChampionsKilled: 0,
				AverageCombatPlayerScore: 0,
				AverageNodeCapture: 0,
				AverageNodeCaptureAssist: 0,
				AverageNodeNeutralize: 0,
				AverageNodeNeutralizeAssist: 0,
				AverageNumDeaths: 0,
				AverageObjectivePlayerScore: 0,
				AverageTeamObjective: 0,
				AverageTotalPlayerScore: 0,
				BotGamesPlayed: 0,
				KillingSpree: 186,
				MaxAssists: 0,
				MaxChampionsKilled: 17,
				MaxCombatPlayerScore: 0,
				MaxLargestCriticalStrike: 955,
				MaxLargestKillingSpree: 11,
				MaxNodeCapture: 0,
				MaxNodeCaptureAssist: 0,
				MaxNodeNeutralize: 0,
				MaxNodeNeutralizeAssist: 0,
				MaxObjectivePlayerScore: 0,
				MaxTeamObjective: 0,
				MaxTimePlayed: 3977,
				MaxTimeSpentLiving: 1324,
				MaxTotalPlayerScore: 0,
				MostChampionKillsPerSession: 17,
				MostSpellsCast: 0,
				NormalGamesPlayed: 0,
				RankedPremadeGamesPlayed: 0,
				RankedSoloGamesPlayed: 0,
				TotalAssists: 452,
				TotalChampionKills: 399,
				TotalDamageDealt: 6546945,
				TotalDamageTaken: 1212158,
				TotalDeathsPerSession: 341,
				TotalDoubleKills: 38,
				TotalFirstBlood: 0,
				TotalGoldEarned: 612143,
				TotalHeal: 146878,
				TotalMagicDamageDealt: 2461564,
				TotalMinionKills: 6226,
				TotalNeutralMinionsKilled: 1327,
				TotalNodeCapture: 0,
				TotalNodeNeutralize: 0,
				TotalPentaKills: 0,
				TotalPhysicalDamageDealt: 3582459,
				TotalQuadraKills: 1,
				TotalSessionsLost: 21,
				TotalSessionsPlayed: 50,
				TotalSessionsWon: 29,
				TotalTripleKills: 6,
				TotalTurretsKilled: 46,
				TotalUnrealKills: 0
			}
		}
		],
		ModifyDate: 1401633958000,
		Solo5sLeague: {
			Entries: [
			{
				Division: "I",
				IsFreshBlood: false,
				IsHotStreak: false,
				IsInactive: false,
				IsVeteran: false,
				LeaguePoints: 0,
				MiniSeries: {
					Losses: 0,
					Progress: "",
					Target: 0,
					Wins: 0
				},
				PlayerOrTeamId: "20227914",
				PlayerOrTeamName: "Lologarithm",
				Wins: 28
			}
			],
			Name: "Ryze's Heralds",
			ParticipantId: "",
			Queue: "RANKED_SOLO_5x5",
			Tier: "GOLD"
		},
		Solo3sLeague: {
			Entries: null,
			Name: "",
			ParticipantId: "",
			Queue: "",
			Tier: ""
		},
		RankedTeamLeagues: null,
		ExpireTime: 1401909894
	}
});